# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"


  config.vm.network "forwarded_port", guest: 80, host: 8080

  #config.vm.synced_folder "../data", "/vagrant_data
  
  #Provider-specific configuration s
  
  config.vm.provider "virtualbox" do |vb|
  
  vb.gui = true
  
  vb.memory = "4096"
  end

 
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  SHELL
end